export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const INIT_SWEATERS = "INIT_SWEATERS";
export const LOADING_SWEATERS = "LOADING_SWEATERS";
export const FAILED_SWEATERS = "FAILED_SWEATERS";
export const ADD_SELECTED = "ADD_SELECTED";
export const REMOVE_SELECTED = "REMOVE_SELECTED";
