export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const INIT_SWEATERS = "INIT_SWEATERS";
export const LOADING_SWEATERS = "LOADING_SWEATERS";
export const FAILED_SWEATERS = "FAILED_SWEATERS";
